"""Git 钩子安装脚本（版本一致性校验 + 暂存）

@Author: 花海
@Date: 2026/08/17 21:10
@Description: 将 pre-commit 钩子写入 .git/hooks/，使每次 git commit 时自动：
              校验版本文件一致性（pyproject / __init__ / README 版本一致，不一致阻止提交）
              并暂存版本文件变更（详见 scripts/version_check.py）。
              版本递增不由本地提交触发（release-only 机制，2026-08-18 整改）：
              正式版由 dev→main 合入时的 release workflow 自动生成（scripts/release_after_merge.py）。
              安装时自动清理旧版 prepare-commit-msg 钩子（此前按提交前缀自动递增版本的机制已废弃）。
              .git/hooks 不入库，每个 clone 后需执行一次本脚本。
              用法：
                python scripts/install_hooks.py            # 安装钩子
                python scripts/install_hooks.py --uninstall # 卸载钩子（恢复备份）
"""

from __future__ import annotations

import stat
import subprocess
import sys
from pathlib import Path

# 钩子文件内标记（识别本脚本生成的钩子，避免误覆盖/误删他人钩子）
_HOOK_MARKER = "# AUTO-VERSION-BUMP hook (generated by scripts/install_hooks.py)"
_HOOK_NAME = "pre-commit"
# 旧版钩子名（prepare-commit-msg 按提交前缀自动递增版本，2026-08-18 release-only 整改后废弃，
# 安装/卸载时自动清理迁移）
_OLD_HOOK_NAME = "prepare-commit-msg"


def _repo_root() -> Path:
    """定位仓库根目录（scripts/ 的上一级）。

    :return: 仓库根目录
    """
    return Path(__file__).resolve().parents[1]


def _git_dir(repo_root: Path) -> Path:
    """获取 git 元数据目录（支持 worktree，.git 可能为文件而非目录）。

    :param repo_root: 仓库根目录
    :return: git 元数据目录绝对路径
    """
    result = subprocess.run(
        ["git", "rev-parse", "--git-dir"],
        cwd=str(repo_root), capture_output=True, text=True, encoding="utf-8",
    )
    if result.returncode != 0:
        raise RuntimeError(f"git rev-parse --git-dir 失败: {result.stderr.strip()}")
    path = Path(result.stdout.strip())
    return path if path.is_absolute() else (repo_root / path).resolve()


def _hook_script(repo_root: Path) -> str:
    """生成钩子脚本内容（sh 脚本，调用 version_check.py）。

    :param repo_root: 仓库根目录
    :return: 钩子脚本文本
    """
    # Git for Windows 的 sh 中反斜杠是转义符，统一转换为正斜杠
    python = sys.executable.replace("\\", "/")
    root = str(repo_root).replace("\\", "/")
    return (
        "#!/bin/sh\n"
        f"{_HOOK_MARKER}\n"
        f"REPO_ROOT='{root}'\n"
        f"PYTHON='{python}'\n"
        '"$PYTHON" "$REPO_ROOT/scripts/version_check.py"\n'
    )


def _remove_hook(hook_path: Path) -> None:
    """删除本脚本生成的钩子文件（含旧版 prepare-commit-msg 迁移清理）。

    :param hook_path: 钩子文件路径
    """
    if hook_path.exists() and _HOOK_MARKER in hook_path.read_text(encoding="utf-8"):
        hook_path.unlink()
        print(f"[install-hooks] 已删除钩子 {hook_path.name}")


def install(repo_root: Path) -> None:
    """安装 pre-commit 钩子（已存在的非本脚本钩子先备份为 .bak），并清理旧版钩子。

    :param repo_root: 仓库根目录
    """
    hooks_dir = _git_dir(repo_root) / "hooks"

    # 迁移清理：删除旧版 prepare-commit-msg 钩子（release-only 整改废弃的自动递增机制）
    _remove_hook(hooks_dir / _OLD_HOOK_NAME)

    hook_path = hooks_dir / _HOOK_NAME
    if hook_path.exists() and _HOOK_MARKER not in hook_path.read_text(encoding="utf-8"):
        backup = hook_path.with_suffix(hook_path.suffix + ".bak")
        if backup.exists():
            raise RuntimeError(
                f"备份文件已存在（{backup}），请先处理后再安装，避免覆盖既有钩子"
            )
        hook_path.rename(backup)
        print(f"[install-hooks] 检测到既有钩子，已备份为 {backup.name}")

    hook_path.write_text(_hook_script(repo_root), encoding="utf-8")
    # Unix 下设置可执行位（Git for Windows 实际通过 sh 执行，此步仅兼容类 Unix 环境）
    hook_path.chmod(hook_path.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    print(f"[install-hooks] 已安装 {_HOOK_NAME} 钩子 -> {hook_path}")
    print("[install-hooks] 每次 git commit 将校验版本一致性并暂存版本文件；版本递增由 dev→main 合入时 release workflow 自动完成")


def uninstall(repo_root: Path) -> None:
    """卸载钩子：删除本脚本生成的钩子（含旧版 prepare-commit-msg），存在备份时恢复。

    :param repo_root: 仓库根目录
    """
    hooks_dir = _git_dir(repo_root) / "hooks"

    _remove_hook(hooks_dir / _HOOK_NAME)
    _remove_hook(hooks_dir / _OLD_HOOK_NAME)

    backup = (hooks_dir / _HOOK_NAME).with_suffix((hooks_dir / _HOOK_NAME).suffix + ".bak")
    if backup.exists():
        backup.rename(hooks_dir / _HOOK_NAME)
        print(f"[install-hooks] 已恢复备份钩子 -> {hooks_dir / _HOOK_NAME}")


def main() -> int:
    """入口：解析参数并安装/卸载钩子。

    :return: 退出码
    """
    repo_root = _repo_root()
    try:
        if "--uninstall" in sys.argv:
            uninstall(repo_root)
        else:
            install(repo_root)
    except Exception as exc:  # noqa: BLE001 - 安装失败给出可读错误
        print(f"[install-hooks] 错误：{exc}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
