"""Git 钩子安装脚本（自动版本管理）

@Author: 花海
@Date: 2026/08/17 21:10
@Description: 将 prepare-commit-msg 钩子写入 .git/hooks/，使每次 git commit 时自动
              按提交前缀递增版本号（详见 scripts/version_bump.py）。
              .git/hooks 不入库，每个 clone 后需执行一次本脚本。
              用法：
                python scripts/install_hooks.py            # 安装钩子
                python scripts/install_hooks.py --uninstall # 卸载钩子（恢复备份）
"""

from __future__ import annotations

import os
import stat
import subprocess
import sys
from pathlib import Path

# 钩子文件内标记（识别本脚本生成的钩子，避免误覆盖/误删他人钩子）
_HOOK_MARKER = "# AUTO-VERSION-BUMP hook (generated by scripts/install_hooks.py)"
_HOOK_NAME = "prepare-commit-msg"


def _repo_root() -> Path:
    """定位仓库根目录（scripts/ 的上一级）。

    :return: 仓库根目录
    """
    return Path(__file__).resolve().parents[1]


def _git_dir(repo_root: Path) -> Path:
    """获取 git 元数据目录（支持 worktree，.git 可能为文件而非目录）。

    :param repo_root: 仓库根目录
    :return: git 元数据目录绝对路径
    """
    result = subprocess.run(
        ["git", "rev-parse", "--git-dir"],
        cwd=str(repo_root), capture_output=True, text=True, encoding="utf-8",
    )
    if result.returncode != 0:
        raise RuntimeError(f"git rev-parse --git-dir 失败: {result.stderr.strip()}")
    path = Path(result.stdout.strip())
    return path if path.is_absolute() else (repo_root / path).resolve()


def _hook_script(repo_root: Path) -> str:
    """生成钩子脚本内容（sh 脚本，调用 version_bump.py）。

    :param repo_root: 仓库根目录
    :return: 钩子脚本文本
    """
    # Git for Windows 的 sh 中反斜杠是转义符，统一转换为正斜杠
    python = sys.executable.replace("\\", "/")
    root = str(repo_root).replace("\\", "/")
    return (
        "#!/bin/sh\n"
        f"{_HOOK_MARKER}\n"
        f"REPO_ROOT='{root}'\n"
        f"PYTHON='{python}'\n"
        '"$PYTHON" "$REPO_ROOT/scripts/version_bump.py" "$1" "$2"\n'
    )


def install(repo_root: Path) -> None:
    """安装 prepare-commit-msg 钩子（已存在的非本脚本钩子先备份为 .bak）。

    :param repo_root: 仓库根目录
    """
    # 钩子必须位于 <git-dir>/hooks/ 子目录（git 仅在 hooks/ 下查找并执行钩子，
    # 2026-08-18 修复：此前直接写 <git-dir>/prepare-commit-msg 导致钩子从未触发）
    hook_path = _git_dir(repo_root) / "hooks" / _HOOK_NAME
    if hook_path.exists() and _HOOK_MARKER not in hook_path.read_text(encoding="utf-8"):
        backup = hook_path.with_suffix(hook_path.suffix + ".bak")
        if backup.exists():
            raise RuntimeError(
                f"备份文件已存在（{backup}），请先处理后再安装，避免覆盖既有钩子"
            )
        hook_path.rename(backup)
        print(f"[install-hooks] 检测到既有钩子，已备份为 {backup.name}")

    hook_path.write_text(_hook_script(repo_root), encoding="utf-8")
    # Unix 下设置可执行位（Git for Windows 实际通过 sh 执行，此步仅兼容类 Unix 环境）
    hook_path.chmod(hook_path.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    print(f"[install-hooks] 已安装 {_HOOK_NAME} 钩子 -> {hook_path}")
    print("[install-hooks] 后续每次 git commit 将按提交前缀自动递增版本号（docs/chore 与 merge/revert 除外）")


def uninstall(repo_root: Path) -> None:
    """卸载钩子：删除本脚本生成的钩子，存在备份时恢复。

    :param repo_root: 仓库根目录
    """
    hook_path = _git_dir(repo_root) / _HOOK_NAME
    if hook_path.exists() and _HOOK_MARKER not in hook_path.read_text(encoding="utf-8"):
        print(f"[install-hooks] {hook_path} 非本脚本生成的钩子，跳过卸载")
        return
    backup = hook_path.with_suffix(hook_path.suffix + ".bak")
    if hook_path.exists():
        hook_path.unlink()
        print(f"[install-hooks] 已删除 {_HOOK_NAME} 钩子")
    if backup.exists():
        backup.rename(hook_path)
        print(f"[install-hooks] 已恢复备份钩子 -> {hook_path}")


def main() -> int:
    """入口：解析参数并安装/卸载钩子。

    :return: 退出码
    """
    repo_root = _repo_root()
    try:
        if "--uninstall" in sys.argv:
            uninstall(repo_root)
        else:
            install(repo_root)
    except Exception as exc:  # noqa: BLE001 - 安装失败给出可读错误
        print(f"[install-hooks] 错误：{exc}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
